name: "Deploy"

on:
    push:
        branches: [main, release, develop]

permissions:
    id-token: write
    contents: read

jobs:
    set_environment:
        runs-on: ubuntu-latest
        outputs:
            mapped_environment: ${{ steps.branch_map.outputs.environment }}

        steps:
            - id: branch_map
              run: |
                  BRANCH_NAME="${{ github.ref_name }}"
                  ENVIRONMENT=""

                  case "$BRANCH_NAME" in
                    "develop")
                      ENVIRONMENT="dev"
                      ;;
                    "release")
                      ENVIRONMENT="hom"
                      ;;
                    "main")
                      ENVIRONMENT="prod"
                      ;;
                    *)
                      echo "Branch $BRANCH_NAME não mapeada para um ambiente de deploy. Abortando."
                      exit 1
                      ;;
                  esac

                  echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
                  echo "Ambiente mapeado: $ENVIRONMENT"

    deploy:
        needs: set_environment
        if: success() && needs.set_environment.outputs.mapped_environment != ''
        uses: ./.github/workflows/terraform.yaml
        with:
            environment: ${{ needs.set_environment.outputs.mapped_environment }}
        secrets:
            application-port: ${{ secrets.APPLICATION_PORT }}
            aws-assume-role-arn: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
            aws-region: ${{ secrets.AWS_REGION }}
            aws-statefile-s3-bucket: ${{ secrets.AWS_STATEFILE_S3_BUCKET }}
            aws-lock-dynamodb-table: ${{ secrets.AWS_LOCK_DYNAMODB_TABLE }}
            aws-access-key: ${{ secrets.AWS_APP_ACCESS_KEY }}
            aws-secret-key: ${{ secrets.AWS_APP_SECRET_KEY }}
            database-password: ${{ secrets.DATABASE_PASSWORD }}
            database-username: ${{ secrets.DATABASE_USERNAME }}
            database-host: ${{ secrets.DATABASE_HOST }}
            database-port: ${{ secrets.DATABASE_PORT }}
            database-name: ${{ secrets.DATABASE_NAME }}
            mercado-pago-access-token: ${{ secrets.MERCADO_PAGO_ACCESS_TOKEN }}
            mercado-pago-collector-id: ${{ secrets.MERCADO_PAGO_COLLECTOR_ID }}
            mercado-pago-pos-id: ${{ secrets.MERCADO_PAGO_POS_ID }}
            mercado-pago-base-url: ${{ secrets.MERCADO_PAGO_BASE_URL }}
            aws-payment-to-order-queue-url: ${{ secrets.AWS_PAYMENT_TO_ORDER_QUEUE_URL }}
            aws-order-to-payment-queue-url: ${{ secrets.AWS_ORDER_TO_PAYMENT_QUEUE_URL }}
