import { MigrationInterface, QueryRunner } from "typeorm";

export class InitPaymentsTable1704475200000 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE "payments" (
                "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                "value" decimal(10, 2) NOT NULL,
                "qr_code" text,
                "external_reference" varchar NOT NULL,
                "order_id" varchar NOT NULL,
                "customer_id" varchar NOT NULL,
                "status" varchar(20) NOT NULL,
                "created_at" timestamp DEFAULT current_timestamp,
                "updated_at" timestamp DEFAULT current_timestamp,
                "deleted_at" timestamp
            );

            CREATE INDEX idx_payments_external_reference ON payments USING hash(external_reference);
            CREATE INDEX idx_payments_status ON payments USING hash(status);
            CREATE INDEX idx_payments_order_id ON payments USING hash(order_id);

            CREATE OR REPLACE FUNCTION update_timestamp() RETURNS trigger AS $$
            BEGIN
                NEW.updated_at = current_timestamp;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DO $$
            DECLARE tbl_name text;
            BEGIN
                FOR tbl_name IN
                    SELECT table_name FROM information_schema.columns WHERE column_name = 'updated_at'
                LOOP
                    EXECUTE format('
                        CREATE TRIGGER set_updated_at_%I
                        BEFORE UPDATE ON %I
                        FOR EACH ROW
                        EXECUTE FUNCTION update_timestamp();',
                        tbl_name,
                        tbl_name
                    );
                END LOOP;
            END;
            $$;
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            DROP TABLE IF EXISTS "payments" CASCADE;
            DROP FUNCTION IF EXISTS update_timestamp() CASCADE;
        `);
    }
}
