import { MigrationInterface, QueryRunner } from "typeorm";

export class InitPaymentsTable1704475200000 implements MigrationInterface {
    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            CREATE TABLE IF NOT EXISTS "payments" (
                "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                "value" decimal(10, 2) NOT NULL,
                "qr_code" text,
                "external_reference" varchar NOT NULL,
                "order_id" varchar NOT NULL,
                "customer_id" varchar NOT NULL,
                "status" varchar(20) NOT NULL,
                "created_at" timestamp DEFAULT current_timestamp,
                "updated_at" timestamp DEFAULT current_timestamp,
                "deleted_at" timestamp
            );

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_payments_external_reference'
                ) THEN
                    EXECUTE 'CREATE INDEX idx_payments_external_reference ON payments USING hash(external_reference)';
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_payments_status'
                ) THEN
                    EXECUTE 'CREATE INDEX idx_payments_status ON payments USING hash(status)';
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'idx_payments_order_id'
                ) THEN
                    EXECUTE 'CREATE INDEX idx_payments_order_id ON payments USING hash(order_id)';
                END IF;
            END;
            $$;

            CREATE OR REPLACE FUNCTION update_timestamp() RETURNS trigger AS $$
            BEGIN
                NEW.updated_at = current_timestamp;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DO $$
            DECLARE tbl_name text;
            BEGIN
                FOR tbl_name IN
                    SELECT table_name FROM information_schema.columns WHERE column_name = 'updated_at'
                LOOP
                    BEGIN
                        EXECUTE format('
                            CREATE TRIGGER set_updated_at_%I
                            BEFORE UPDATE ON %I
                            FOR EACH ROW
                            EXECUTE FUNCTION update_timestamp();',
                            tbl_name,
                            tbl_name
                        );
                    EXCEPTION
                        WHEN duplicate_object THEN
                            -- Trigger já existe, ignora o erro
                            NULL;
                    END;
                END LOOP;
            END;
            $$;
        `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            DROP TABLE IF EXISTS "payments" CASCADE;
            DROP FUNCTION IF EXISTS update_timestamp() CASCADE;
        `);
    }
}
