create table "payments" (
    "id" int generated by default as identity primary key not null,
    "value" decimal(10, 2) not null,
    "qr_code" text,
    "external_reference" varchar not null,
    "order_id" varchar not null,
    "customer_id" varchar not null,
    "status" varchar(20) not null,
    "created_at" timestamp default current_timestamp,
    "updated_at" timestamp default current_timestamp,
    "deleted_at" timestamp
);

create index idx_payments_external_reference on payments using hash(external_reference);

create index idx_payments_status on payments using hash(status);

create index idx_payments_order_id on payments using hash(order_id);

create
or replace function update_timestamp() returns trigger as $ $ begin new.updated_at = current_timestamp;

return new;

end;

$ $ language plpgsql;

do $ $ declare tbl_name text;

begin for tbl_name in
select
    table_name
from
    information_schema.columns
where
    column_name = 'updated_at' loop execute format(
        'create trigger set_updated_at_%I
          before update on %I
          for each row
          execute function update_timestamp();',
        tbl_name,
        tbl_name
    );

end loop;

end;

$ $;